### ISSUE TITLE
Show move number on stones

### ISSUE THREAD

**Issue by vault101** [SabakiHQ/Sabaki#154]
[Mac OS X] Is it possible to show the move index on every stone? Or is there any switch in the app?

**Comment by yishn** [comment]
No, it's currently not possible to do that. There are some considerations to make when implementing:

* How do we handle custom SGF markers?
* How do we handle two moves on the same place?
* What about the option to only show the last `n` move numbers?

**Comment by aniljava** [comment]
Here are my suggestions.

- How do we handle custom SGF markers?
You mean triangles, squares, ABCD.. ? We can either write the move number first and draw the markers on top. Marker first and number on top. Lets make the move number font small so that both are visible.

If we want to show only one when both are present, We can put an option on menu with "Toggle Move Number" and "Toggle SGF Markers".

- How do we handle two moves on the same place?
The gogui ignores the old move and only shows the last move number at the position. We can either choose that way. Or in settings we can have an option to allow user to choose whether to hide the last move or show at the bottom of the board like traditional kifu. Example,  112 : 39, 83

- What about the option to only show the last n move numbers?
For this too, we let up to user to decide in settings, if they want the numbering to be exact move number or starting at 1 since the last move back.

**Comment by yishn** [comment]
> How do we handle custom SGF markers?
You mean triangles, squares, ABCD.. ? We can either write the move number first and draw the markers on top. Marker first and number on top. Lets make the move number font small so that both are visible.

Drawing the markers on top will obscure the move number and vice versa. Especially with the cross marker and custom labels. Not good. I'm interested how to make the move number font small so that both are visible. Please note that a move number can consist of three digits. Furthermore, how to distinguish custom number labels with move numbers?

> How do we handle two moves on the same place?
The gogui ignores the old move and only shows the last move number at the position. We can either choose that way. Or in settings we can have an option to allow user to choose whether to hide the last move or show at the bottom of the board like traditional kifu. Example, 112 : 39, 83

To be honest, I don't see a use case for move numbers on stones. Since you have the whole game opened already, you can just navigate through the game to get a feeling of placement order. Tracking stones with move numbers only requires a lot of mental effort and I find it very difficult to concentrate on the play itself. The only reason to use move numbers that I can think of is, if you want to convey the move order on a static medium, like a kifu or image.

Should Sabaki get the feature to print or export to an image in the future, I'll gladly add the option to automatically assign move numbers.

**Comment by shuodaowang** [comment]
I think one of the workaround solution is to toggle on the game tree which shows the move number (from the first move) at the top right corner.  but I guess the request was about showing numbers for a sequence moves as it is usually used in some books, so that when the author of the book says move 7, we can know exactly which one he is talking about.  if we can have a feature to select/mark a certain stone as #1, and then the subsequent moves automatically show their corresponding numbers, that'd be very useful in reading some of the books that come with SGF files.  I think it'd be best to show the numbers of the remaining stones, and if one needs to he can move back a few moves to see which stones were killed.

**Comment by scarin** [comment]
显示步数非常的重要。建议参考下multiGo实现的规则
http://ruijiang.com/multigo/chs/

**Comment by UnsignedInt8** [comment]
Showing move numbers is very important for users. Is there any plan to implement it?

**Comment by yishn** [comment]
Care to elaborate?

**Comment by Walther** [comment]
I think there's a grain of truth in this discussion: the current move number is difficult to see / find.

If you don't have the game tree open, you can't see the move number at all:
<img width="1440" alt="screen shot 2017-11-19 at 13 55 06" src="https://user-images.githubusercontent.com/2943750/32990384-53b2e3e2-cd31-11e7-9b37-a6d1df10061e.png">

If you do have the game tree open, the move number is displayed on the scrollbar of the game tree:
<img width="1440" alt="screen shot 2017-11-19 at 13 53 53" src="https://user-images.githubusercontent.com/2943750/32990393-719fa17e-cd31-11e7-85a7-f47f2d44476f.png">
<img width="1440" alt="screen shot 2017-11-19 at 13 53 56" src="https://user-images.githubusercontent.com/2943750/32990398-7daa8d8a-cd31-11e7-8f5d-d987a4110ce3.png">
<img width="1440" alt="screen shot 2017-11-19 at 13 54 01" src="https://user-images.githubusercontent.com/2943750/32990403-8849f456-cd31-11e7-80d2-f759884a3fdc.png">

This is difficult because:
- By default, move number is not visible
- It's a small number as the scrollbar, instead of being highlighted as an important focus item
- It moves while moving in the tree, so you have to actually "hunt for it" with your eyes
