### ISSUE TITLE
new command for clear the go board?

### ISSUE THREAD

**Issue by shuodaowang** [SabakiHQ/Sabaki#204]
Hi,

can we have a quick command (with keyboard shortcut) to clear the go board?  this will be useful for studying patterns in go books.  right now the closest solution is to create a new game, but two steps are needed to have a clear board: "save?" and "confirm the player/board info".

**Comment by Seth-Rothschild** [comment]
Another option might be to just scroll to the top of a given game tree?

A possible problem with such a function would be for the users who *want* to be asked to save. Other than that it should be straightforward to create a new preference to disable the save prompt (which would get you halfway there).

**Comment by dfannius** [comment]
Just scrolling to the top of the tree isn't sufficient if you have added a lot of stones to the root position, since you have to remove them all by hand to set up another position (unless I have missed a shortcut).

**Comment by Seth-Rothschild** [comment]
Ah, I was totally misunderstanding the problem. So the goal is for something like the "clean markup..." but for placed stones? I took a look but I don't understand enough to figure out what's going on with the stone tool in edit tools to have an informed opinion about how hard it would be to change. 

A possible solution might be that placing the _first_ stone in edit mode makes a single element new branch with the stones placed. That would solve this problem (one button to undo all changes) and would do no harm for writing game reviews since I'd imagine having a bunch of extra stones all at once wouldn't be so helpful to have in the main game.

**Comment by dfannius** [comment]
That could work but I think you'd have to be careful about all the edge cases. For example, what happens if you back up from the position-setup node to the root and then start placing more stones? Does it create another branch? You'd also want to confirm that having that empty root node is totally legit SGF or you'd have to do some translation back and forth when loading/saving, which is prone to error (plus having the app's presentation of the tree not match the SGF in the file would make me nervous).

**Comment by Seth-Rothschild** [comment]
> A possible solution might be that placing the first stone in edit mode makes a single element new branch with the stones placed.

It seems that Sabaki *already* adds a new branch so long as a single stone (?!) has been played. It even seems like you can go back to the root and editing will make a new branch (only after a single stone has been played). If that is indeed the status of things I claim this issue can be closed, since you can set the origin node as a hotspot and can even navigate there with a keyboard shortcut.

**Comment by dfannius** [comment]
I may be misunderstanding. Here is the case I am running into (@shuodaowang's may be different):

1. Start a new board with Command-N
2. Click the pencil to go into edit mode
3. Place stones to set up an initial position
4. Leave edit mode
5. Play out some variations

Now I want to go back to an empty board, but to do so I have to go back to the root and erase all the stones by hand (or Command-N). Are you saying that I should insert step 1a. Place the first stone as a move, rather than as an edit, then go into edit mode (which will indeed add a new node now) to place the rest? That is what I have to do in CGoban too, and it's pretty annoying.

**Comment by Seth-Rothschild** [comment]
Exactly, though you could also include step 1b. Press up to go to empty board, and it might not be as bad? I'd probably also Command-B to set the empty board as a hotspot so that you can f2 to go back to the empty board. What's strange is if you

1. Play steps 1-5 including 1a and 1b
2. Remove the stone played in 1a

things seem to work just fine so it's not clear why that's not what happens by default. We do seem to be venturing into "bug" territory rather than the initial issue though.

**Comment by dfannius** [comment]
There is enough cognitive friction for me (personally) in placing the very first stone of the position as a move rather than an edit every time that I much prefer the "simpler" Command-N / Don't Save / OK method, in which at least every step that I take has natural semantics. That said, a shortcut to clear the board would be even nicer :)

**Comment by yishn** [comment]
What I think @Seth-Rothschild means is to play a random stone as a move before editing the empty board node, i.e:

1. Start a new file
2. Play random stone as move, say Tengen
3. Go back to the root node
4. Place stones to set an initial position (Sabaki will create a new variation for that)
5. Delete random move played in 2.
6. Play variations

This way, you'll always have an empty board at the root node. 

As to why Sabaki doesn't create a variation when placing stones in an empty file: It is to allow the user to place free handicap stones.
