### ISSUE TITLE
Show white player before black player

### ISSUE THREAD

**Issue by raspingbard** [SabakiHQ/Sabaki#234]
Every go-related software I’ve seen shows the white player first followed by the black player second on both the screen and the game title/record.  The “New Game” panel has this switched around.  This has thrown me off a few times.

**Comment by yishn** [comment]
In the code, when we store information for both players (like capture count), we use an array of length 2 where the first entry corresponds to the black player, and the second entry to the white player. This will get confusing quickly for the developers, that's why I'm closing this issue. Also, users who are used to the current order will have to rewire their brains.

Furthermore, the current order makes more sense since black makes the first move (I guess this only applies to people who are reading from left to right).
