### ISSUE TITLE
Placement of handi stones

### ISSUE THREAD

**Issue by d7urban** [SabakiHQ/Sabaki#337]
Is there a way to change where the handicap stones are, specifically for  3 handi games? Crazy Stone has the top left corner empty, while Sabaki has the bottom right corner empty. (I also think KGS does it the same way as Crazy Stone.)
The issue came up when I wanted to play Crazy Stone against other engines in Sabaki and the placements were different.

**Comment by yishn** [comment]
Handicap stones are just normal placed stones. You can always enter edit mode and use the stone tool to remove or add stones yourself. But if noone has any objections, we could change the default placement of the stones of a three handicap game to match KGS and Crazy Stone.

**Comment by fohristiwhirl** [comment]
I'm not immediately sure how this would affect the NGF / GIB parsers. I apparently used getHandicapPlacement() to position the stones, which presumably means what we have now was compatible with those formats.

**Comment by fohristiwhirl** [comment]
But if desired, it would be easy enough to make it take some sort of boolean to use the Tygem / Wbaduk placement, as opposed to KGS.

**Comment by yishn** [comment]
@fohristiwhirl So Tygem's and Wbaduk's placement of handicap stones are different from KGS? If that's the case, then we probably shouldn't change this.

**Comment by fohristiwhirl** [comment]
KGS puts the 3rd stone on Q4, while Tygem (and I think WBaduk) put it on D16.

Of course the SGF files from KGS etc should have AB[] tags. But for GIB and NGF we just trust that they are where we expect.

**Comment by ikirill** [comment]
I also think Sabaki should change the default 3 stone placement (I've been editing it in my own games). AGA rules (http://www.usgo.org/files/pdf/completerules.pdf#page=2) say that the top-left corner is empty with 3 handicap stones.

AFAIK, this is considered traditional because you're looking at the board from Black's point of view, and the empty corner where White will play is close to White sitting at the board. So this is the same reason that the first 4-3 point Black plays is traditionally in the top-right corner, closer to the right side (not the top side).

**Comment by fohristiwhirl** [comment]
Well, PR at #339
