### ISSUE TITLE
Offer a default keyboard shortcut to display the score Estimation

### ISSUE THREAD

**Issue by wctgit** [SabakiHQ/Sabaki#345]
Currently, you must click on the hamburger and Estimate to show an estimation. It would be much more convenient to have a default keyboard shortcut assigned to this action, and especially to allow multiple re-estimations without having to click the x to close the score estimator display (since the score estimation may change each time, sometimes by a lot, and clicking x, then hamburger, then Estimate is way too many steps just to get a quick re-estimate).

**Comment by yishn** [comment]
Can you suggest a fitting keyboard shortcut? What about scoring the game? I feel like if 'Estimate' has a keyboard shortcut, then 'Score' should have one, too.

**Comment by wctgit** [comment]
Well, I'm not sure what kind of keyboard shortcut style you prefer. You've got Ctrl-I for Game Info, and Ctrl-Shift-M for Manage Games, which are two I'm currently using frequently. A straightforward extension of that would be Ctrl-E, Ctrl-S, but Ctrl-S is usually Save, so maybe Ctrl-Shift-E, Ctrl-Shift-S? Alternatively, you could use some of the F keys, like F5, F6, or whatever. Finally, you could offer a default shortcut and offer users to be able to edit the shortcuts, but this would take more work.

Another possibility I can think of, based on my own mnemonic would be Ctrl-= for Estimate, and Ctrl-Shift-= for Score.

**Comment by yishn** [comment]
<kbd>Ctrl+E</kbd> is 'Toggle Edit Mode', <kbd>Ctrl+Shift+S</kbd> is 'Save under...', so... not really an option. <kbd>F5</kbd> and <kbd>F6</kbd> are currently reserved for GTP engines, and keyboard shortcuts with special characters like <kbd>=</kbd> are bad for international keyboards. 

I've given some thought about this and I didn't find any good keyboard shortcuts for Estimate and Score, so that's why I was asking.

**Comment by wctgit** [comment]
Do keyboard shortcuts necessarily require a modifier key? Why not just 'E' and 'S'? How about Ctrl-NumPad+ for Estimate and Ctrl-Enter and/or Ctrl-NumPadEnter for Score? Numpad keys no good either? Honestly, anything is better than nothing, IMHO. Use Ctrl-7 or Ctrl-P for all I care. :-) I'll learn whatever the key is.

**Comment by yishn** [comment]
<kbd>Ctrl+Plus</kbd> and <kbd>Ctrl+Minus</kbd> are controlling the zoom. Differentiating between <kbd>Enter</kbd> and <kbd>NumPadEnter</kbd> is not a very good idea, also some laptops don't even have a numpad. Press <kbd>Ctrl+P</kbd> to pass. <kbd>Ctrl+{1-9}</kbd> are reserved for edit tools. <kbd>Ctrl+0</kbd> resets the zoom.

**Comment by yishn** [comment]
Keyboard shortcuts don't necessarily require a modifier key. But it's good style to have one. Because you won't be able to activate a keyboard shortcut when, for example, a textbox is focused, if you don't have a modifier key.

**Comment by yishn** [comment]
I think we can still use <kbd>K</kbd>, <kbd>U</kbd>, <kbd>D</kbd> with <kbd>Ctrl</kbd>...

**Comment by wctgit** [comment]
You can also use Ctrl-Alt, Alt-Shift, and Ctrl-Alt-Shift. I used to work for a company that made a GUI for programmers, and we ended up using all sorts of combinations (as well as user-customizable).

**Comment by weaver299** [comment]
What about Ctrl-Shift-E for **E**stimate, and Ctrl-Shift-R for sco**R**e?

Apologies if those have already been addressed and I didn't catch it... I saw Ctrl-Shift-E was mentioned but it didn't look like that _specific_ one had been ruled out.  I tried these while viewing a game in edit mode and not edit mode (tested on Mac only) and they didn't seem to do anything..

Command-Shift-E/R on Mac would preferable but Control-Shift-E/R would be fine too.

I would love this feature too, because I'm often stepping through my games and trying to observe the change in score estimate... I was actually thinking it would be cool if we could still navigate the game tree without turning the estimate off at all.. but just the hotkeys would be a big help.

Thanks for your excellent work!  Best SGF UI I've ever used...
