### ISSUE TITLE
Show multiple shape annotations when possible, ordered by 'priority'

### ISSUE THREAD

**Issue by wctgit** [SabakiHQ/Sabaki#347]
Enhancement request: In the shape annotation text box, you could list how the current move made more than one shape, if applicable. E.g.: Atari, Cut, Tiger's Mouth, Hane.

It's just an idea, and low priority. I could see it getting cluttery, but perhaps if it was disabled by default, and you could turn it on optionally (to learn basic shapes), then that could be a good compromise.

**Comment by yishn** [comment]
To be honest, the shape library of Sabaki isn't the best, and I certainly won't trust it enough to let a Go beginner learn from it. It's more like a mnemonic, so that one can remember the intention behind the move more easily, if the move doesn't have a title already. It's not the goal of Sabaki to provide some sort of teaching tool, that's a bit out of scope...

This is a pretty good idea, so I think this can be turned into some standalone Go teaching tool.
