### ISSUE TITLE
Don't auto switch engine color

### ISSUE THREAD

**Issue by qwiffs** [SabakiHQ/Sabaki#353]
If I run a manual vs. AI game (manual is black and engine is white), when I modify the engine's selected move in white order, the engine will automatically run in black order. 
However, GoGui does not have this bad function at all. 
Please add the option to remove such bad function that the engine automatically runs in the manual color when I modify the engine's move.

**Comment by geovens** [comment]
I second this. I would prefer an option that AI will only generate any single move when explicitly told to (like after clicking an 'generate move' button).

**Comment by geovens** [comment]
Another two suggestions:  
1. When the GTP engine is thinking, I can't do anything on Sabaki UI. This is obviously on purpose, because Sabaki doesn't want users to mass logic up. But it would be good if I can at least scroll the engine output window to read more output texts than the happens-to-be-in-the-view ones while the engine is thinking.  
2. When a GTP engine is thinking, I can't find a way to stop it. Is ''Engines -> Suspend" supposed to stop it? But when a GTP engine is thinking this command is grayed out. I hope there is a command to forcefully kill the engine process.

**Comment by yishn** [comment]
Generating one move only is already possible in v0.35.0. The next release will allow suspending engines while thinking, and adds a setting to turn off automatic engine move generation.
