### ISSUE TITLE
Deep files hang the app

### ISSUE THREAD

**Issue by fohristiwhirl** [SabakiHQ/Sabaki#563]
Files with very long variations (such as can be produced with random move generators) cause Sabaki to hang, with: `Uncaught (in promise) RangeError: Maximum call stack size exceeded`

Ideally this should succeed, but if not, it should be caught and give a warning. As it stands, it leaves the app in an unusable state.

Here's an example file...
[2019-04-30-17-37-08.sgf.txt](https://github.com/SabakiHQ/sgf/files/3132245/2019-04-30-17-37-08.sgf.txt)

**Comment by yishn** [comment]
I can open the file and navigate it step by step, but I can reproduce this issue by jumping to the last node after loading the file. Maybe it's because we have to generate the board states for all nodes recursively? But still, 787 should not be near high enough to exceed maximum call stack size. Chrome's maximum call stack size is somewhere in the 10000. This might be avoided if we rewrite `getBoard()` to avoid recursion.

**Comment by fohristiwhirl** [comment]
"I can reproduce this issue by jumping to the last node"

Oh! I had the setting on that does this automatically. Yes, without that I can load it and get the same result as you.
