### ISSUE TITLE
Some advices:

### ISSUE THREAD

**Issue by lj739** [SabakiHQ/Sabaki#638]
Some advices:
1.	Analyzer engine should be stopped when F4 key be pressed again, or it would consume gpu power when another non-analyzer engine is trying to generate a move.
2.	When doing analyze, wherever the human player choose a point to place a stone, Analyzer engine should stop analyzing and the in turn engine generate a move automatically, no need for press F10.
3.	When a human player involved in a game with two engine loaded, the genmove key (F10) and toggle analysis key (F4) usually need to be pressed down again and again, but these two keys are very small on keyboard and not easy to reach without distracting someone’s mind on the board. I sincerely wish you to map the genmove key (F10) to right mouse key single press down , and map toggle analysis key (F4) to space key.

**Comment by yishn** [comment]
Regarding 1: It's fixed now

Regarding 2: If you assign an engine to a player, the engine will automatically generate a move when it's their turn.

Regarding 3: Why do you need to press F4 again and again? Also if you assign the engine to players, you wouldn't need to press F10 repeatedly. Mapping F4 to Space instead is a bad idea, since you can't activate it, e.g. when you're writing a comment (a text box is focused). Also the right mouse button is reserved for context menus. If we make it to generate a move it will be confusing and can be triggered accidentally too easily.
