### ISSUE TITLE
Avast antivirus triggers on the installation files

### ISSUE THREAD

**Issue by larspensjo** [SabakiHQ/Sabaki#674]
If I try to run the 32-bit or 64-bit executable installation files, Avast will stop me. I think it is a false positive.

See https://www.virustotal.com/gui/file/0f448dd4451e3d2165b3fb94e56fff2d6f4036d86de9f35c706b8a2aa136be88/detection

**Comment by GopherAl** [comment]
The same thing happens to me with the 64-bit files. I have reported it to Avast several times since v0.50.1 was released but they have done nothing. Actually the same thing usually happens with new Sabaki releases but usually they do their checks and pass the installation. However I have been prevented from installing v0.50.1.

My attempts to install v0.50.1 stalled when it thought it had found **Win32:MdeClass** malware in **old-installer.exe**.

![image](https://user-images.githubusercontent.com/47664082/77364137-a98c6700-6d9f-11ea-9964-88bd2d883576.png)

**Comment by yishn** [comment]
Please report it as a false positive whenever possible. We don't have any control over Antivirus software.

**Comment by GopherAl** [comment]
@larspensjo Have you been able to install v0.50.1? I'm wondering if I have a problem with my PC after doing several installs & uninstalls. I have reported false positives to Avast many times with no response from them.

**Comment by GopherAl** [comment]
@larspensjo I managed to install v0.50.1 after doing a "Restore and add exception" on the problem files in Avast Virus Chest.

**Comment by larspensjo** [comment]
Riht, I used an Avast "exception".

Den tis 31 mars 2020 kl 13:47 skrev GopherAl <notifications@github.com>:

**Comment by mute2120** [comment]
This isn't just a false positive.  Reading through a couple of the close bug reports and it is being caught by avast, malwarebytes, and windows defender.
