### ISSUE TITLE
Feature Suggestion: Stone Score

### ISSUE THREAD

**Issue by simonguoxm** [SabakiHQ/Sabaki#693]
Is it possible to add stone score ? Stone score is very simple. It is the number of stones on the board. OGS has this stone score. 

![image](https://user-images.githubusercontent.com/4695131/79252965-15666a80-7e48-11ea-976e-08f85246b1fb.png)

**Comment by yishn** [comment]
Why would you need the number of stones on the board?

**Comment by simonguoxm** [comment]
The original Go game rule counts the number of stones on the board. This simple feature can help players to know the original rule, and finally understand the difference between other counting methods (such as territory counting, area counting etc), and how these counting methods evolve to current rules (Chinese rule, Japanese rules, etc)

**Comment by yishn** [comment]
> The original Go game rule counts the number of stones on the board. 

This is a little bit misdirecting; it only works because both players are supposed to fill out the whole board, which, in practice, is never done digitally (also quite tedious). If the players did not fill out everything (this is almost always the case), the stone count is useless.

Thus, a better, modern way to count (which is equivalent to traditional Chinese stone scoring) is using the area score with group tax. Sabaki already provides area score, so you just need to deduct the group tax to get to the stone score.

**Comment by simonguoxm** [comment]
You are right -- Stone count is practical only on a small board (like 7x7)  . On a bigger board it is tedious. That's why territory counting and area counting come into being later. Because of the sequence, we should use stone score to get territory score or area score, not backward. Reversing calculation (like deduct group tax from area score) may lead to unforeseen issues.

**Comment by yishn** [comment]
Since stone count is not practical at all and might even lead to confusion to beginners, I'm not willing to include it.
