### ISSUE TITLE
SGF editing issue

### ISSUE THREAD

**Issue by proskurius** [SabakiHQ/Sabaki#696]
Hello, I stumbled on an issue with sabaki. When you create a Go problem with variations and a solution, if you decide to change the original position a little, it creates a new branch outside of the main problem tree. So if you need to change something in the original position you also have to delete all the variations and make new ones from scratch? Is there a way to fix this?

**Comment by yishn** [comment]
This is by design, since editing positions in place could have consequences for the whole subtree (can implicitly cause the subtree to misbehave, e.g. to contain moves that are being played on top of other stones) that the user didn't intend.

The only editing operations that Sabaki allows for those kind of "dangerous" edits, are the copy/cut/paste variation mechanisms, thus a possible workaround can be: Suppose, you have a tree that looks like the following and you want to add/remove some stones from the root node `x`:

~~~
x----.
| \   \
1 2 … n
~~~

First, copy node `x`. Navigate to `x` and make your desired changes, which creates a node `x'`. Then you'll have a tree that looks like this:

~~~
x------.
| \   \ \
1 2 … n x'
~~~

Now paste your variation on top of `x'`, yielding:

~~~
x------.
| \   \ \
1 2 … n x'---.
        | \   \
        1'2'… n'
~~~

Finally, do a 'Flatten' operation on the `x'` node, resulting in your desired edit.

**Comment by proskurius** [comment]
Thanks, I'll give it a shot.
