### ISSUE TITLE
can sabaki support ssh remote function between two windows computers

### ISSUE THREAD

**Issue by zzhmot** [SabakiHQ/Sabaki#722]
i am wondering if sabaki in windows system support ssh remote GTP to another windows pc having katago.   before i use ssh command of sabaki in windows system, do i need to use SSH tool, like putty log in another windows pc at first, then i use SSH command in sabaki to setup connection between two windows pc?
another question is : if setting-up ssh connection between 2 pcs needs  password verification, how should i configure sabaki's ssh command to deal with?
 i am really a novice for sabaki,  could anyone help me on those questions?  thanks in advance!

**Comment by wirelesstevmc** [comment]
I was trying this with two computers running linux. I have setup ssh-key so that no authentication is required between the two machines but I have not been able to figure out how to get this working. I can for example run the katago executable remotely with:
$ ssh user@linux1 katago gtp

If I try creating a machine entry with the above it just spins indefinitely attempting to start the engine.

I think the shell that sabaki runs is rather limited and it simply doesn't understand networking protocols or ports. It probably can be done if the client is recompiled with these options.

**Comment by zzhmot** [comment]
> I was trying this with two computers running linux. I have setup ssh-key so that no authentication is required between the two machines but I have not been able to figure out how to get this working. I can for example run the katago executable remotely with:
> $ ssh user@linux1 katago gtp
> 
> If I try creating a machine entry with the above it just spins indefinitely attempting to start the engine.
> 
> I think the shell that sabaki runs is rather limited and it simply doesn't understand networking protocols or ports. It probably can be done if the client is recompiled with these options.

thanks for your answers!

**Comment by apetresc** [comment]
I've confirmed through manual testing that this does already work without any changes - as long as the engine is set up correctly and key-based authentication is used. Perhaps some documentation can be added to explain this, but otherwise this is already resolved.
