### ISSUE TITLE
Does Sabaki support transparent boards?

### ISSUE THREAD

**Issue by HackYardo** [SabakiHQ/Sabaki#747]
I choose a colorful background image and a transparent board image, but I see the default brown board instead of the colorful background.

**Comment by yishn** [comment]
Can you please post your transparent board image so we can reproduce your issue?

**Comment by HackYardo** [comment]
> Can you please post your transparent board image so we can reproduce your issue?

![trans8 svg](https://user-images.githubusercontent.com/57677458/93835349-804a8600-fcb1-11ea-9fee-adc711796ea3.png)

**Comment by yishn** [comment]
Interesting, it's completely transparent 😂 

Normally, Sabaki would detect the main color of the board image. Markers and labels on the board will get the background color as well to improve readability, otherwise label text would collide with the grid and it results in an unreadable mess. Due to this accessibility reason Sabaki unfortunately does not support transparent boards.
