### ISSUE TITLE
Windows install file detected as malware

### ISSUE THREAD

**Issue by danielc007** [SabakiHQ/Sabaki#790]
I downloaded this
https://github.com/SabakiHQ/Sabaki/releases/download/v0.51.1/sabaki-v0.51.1-win-x64-setup.exe
and avast mark it as malware

**Comment by sente361** [comment]
Avast always does this with Sabaki. It is a "false positive"; 99% of anti-virus software does not class Sabaki as malware. You should find the offending file locked in the Avast Virus Chest. You should have no problems after following procedure (or similar; I forget the exact procedure since I have only done this a few times in the relatively distant past):

1. Hover your cursor over the offending file [1st image below]
2. Click the three periods ( ... ) to open "More options" [2nd image below]
3. Click "Restore and add exception" [3rd image below]
4. You should see a "File successfully restored" message [bottom image] 
5. The file should now be back in your Downloads folder (or wherever it was originally) and you should now be able to install Sabaki.

![image](https://user-images.githubusercontent.com/47664082/119587280-b2e4e980-be11-11eb-88d4-2bba785288d5.png)

![image](https://user-images.githubusercontent.com/47664082/119586661-8381ad00-be10-11eb-9a68-21636d5d2eaf.png)

![image](https://user-images.githubusercontent.com/47664082/119587465-1bcc6180-be12-11eb-81ec-532a226b77f5.png)

![image](https://user-images.githubusercontent.com/47664082/119587683-8382ac80-be12-11eb-81b9-2f5041c1f3f8.png)
