### ISSUE TITLE
Feature Suggestion: GLAT's Visual Effects

### ISSUE THREAD

**Issue by psygo** [SabakiHQ/Sabaki#945]
TelegraphGo shared that some of the visual effects he uses in his videos comes from this editor: [GLAT - Go Live Annotation Tool](https://ci-en.net/creator/16891/article/781169#fc8fdf238e) and [Just Go, on Steam](https://store.steampowered.com/app/1862520/Just_Go/).

These are pretty nice, and I wish there was a way to optionally add them to Sabaki, but perhaps it would be better through an extension?

**Comment by HackYardo** [comment]
Pretty cool, but it can be download for free, why Sabaki insert it or extend it?  Non sense in view.

**Comment by apetresc** [comment]
Agreed; the whole idea of that tool is that it works on a screen buffer and therefore any Goban, which is great. I definitely don't think Sabaki is interested in upstreaming confetti animations and the like.

Glad that exists though :) Seems very useful for streamers/commentators.

**Comment by psygo** [comment]
If it seems interesting and useful for streamers/commentators then why would it not be interesting for Sabaki? Aren't they a portion of the users?

**Comment by apetresc** [comment]
Because it already exists as a standalone tool that works on any goban component including Sabaki; to reimplement it in Sabaki would be extremely complex, be strictly less useful (since Sabaki's implementation would work _only_ on Sabaki whereas this one works on anything), and complicate the UI for a feature that is only useful for a very small subset of users who are screen-sharing their Sabaki usage.
