### ISSUE TITLE
GTP `analyze` command

### ISSUE THREAD

**Issue by p3achyjr** [SabakiHQ/Sabaki#946]
Hello! The docs say, for `analyze`, that "The response will terminate when any input is written to stdin."

Is this literally any input, or can newlines suffice?

**Comment by HackYardo** [comment]
It's an unsolved GTP issue since LeelaZero. For GTP, a text protocol of Go programs, **a blank new line means the end of a command output**. While modern Go AIs support analyze command, which output is very long and hard to know the end. Finally LZ standardize it as is, and then Ray, SAI, KataGo follow as far as I know.
A blank newline or any input will stop analyze command. **The end of analyze command output is two blank newlines**.

**Comment by HackYardo** [comment]
It's an unsolved GTP issue since LeelaZero. For GTP, a text protocol of Go programs, **a blank new line means the end of a command output**. While modern Go AIs support analyze command, which output is very long and hard to know the end. Finally LZ standardize it as is, and then Ray, SAI, KataGo follow as far as I know.
A blank newline or any input will stop analyze command. **The end of analyze command output is two blank newlines**.
