### ISSUE TITLE
coordinate notation problem

### ISSUE THREAD

**Issue by jinsw1013** [SabakiHQ/Sabaki#958]
When View -> show Coordinate is A1, it jumps "I" and is displayed from A to T.

**Comment by HackYardo** [comment]
It's fine, it is under the GoTextProtocol standard: [from A to T, excluding I](https://www.lysator.liu.se/~gunnar/gtp/gtp2-spec-draft2/gtp2-spec.html#SECTION000311000000000000000)

**Comment by jinsw1013** [comment]
Oh, I understand. Thank you for letting me know.

**Comment by apetresc** [comment]
It's not just a GTP thing, it's a general convention on most Go interfaces; like, here's OGS:

<img width="745" alt="Screenshot 2024-09-24 at 1 30 44 PM" src="https://github.com/user-attachments/assets/865b03f7-feb1-4f1b-ac0a-a984ccfe994f">

The reasoning is that the letter "I" is too similar to the letter l and the number 1 in many fonts, so its omitted to avoid confusion.

**Comment by HackYardo** [comment]
@apetresc You put the cart before the horse! 

- Every program for the game of Go are based on GoTextProtocol and SmartGameFormat, no matter a bot, a GUI or a server. The two standards are pretty useful and powerful. 
- Another a fact is, the two are too old since 2016 AlphaGo Event. With the development of AI bots, we all need new versions of GTP and SGF, such as how to standardize `leelaz-analyze`, `kata-analyze`, `ownership`, `win-rate`. 

However, no one can write a draft until now. The result: there are no compatibilities in our community. For example, if one reviewed a game with OGS or KaTrain, and then open the game record file with Sabaki (as it is offline and elegant), he have to review the game with Sabaki again. Because most reviewed data generated by OGS or KaTrain will not read by Sabaki, and vice versa...

**Comment by apetresc** [comment]
@HackYardo I don't disagree with your statements, but... what does that have to do with the letter 'I'?

**Comment by HackYardo** [comment]
Sorry to be sort of off-topic. The two standards is what developers always keep in mind while you just forgot.
